#!/bin/sh

alias b='bundle exec'
alias rc='bundle exec rails c'
alias rct='bundle exec rails c -e test'
alias dbc='bundle exec rails dbconsole -p'
alias dbct='bundle exec rails dbconsole -p -e test'
alias dbm='bundle exec rails db:migrate'
alias dbr='bundle exec rails db:rollback'

alias r='bundle exec rails'
alias s='bundle exec rspec'
