#!/bin/bash

alias c='clear'

# xclip clipboard
alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'

# colorize grep
alias grep="grep --color=auto"
alias fgrep="fgrep --color=auto"
alias egrep="egrep --color=auto"

# colorize ls
alias ls="ls --color"

# vim
alias v="run-vim"
alias bv="bundle e run-vim"
