#!/bin/bash

source /usr/share/bash-completion/completions/git

alias g='g'

alias ga="git add"
alias gaa="git add *"

alias gc="git commit"
alias gca="git commit -a"
alias gcan="git commit --amend --no-edit"

alias gph="git push"
alias gphf="git push --force-with-lease"
alias gpl="git pull"
alias gplrb="git pull --rebase"

alias gco="git checkout"

alias gu="git reset"
alias gres="git reset --soft HEAD^"

alias gl="git log --pretty=format:\"%C(yellow)%h %C(magenta)%ad%Cred%d %Creset%s%Cblue [%cn]\" --decorate --date=short -20"
alias gla="git log --pretty=format:\"%C(yellow)%h %C(magenta)%ad%Cred%d %Creset%s%Cblue [%cn]\" --decorate --date=short"
alias glt='gl --graph --all'
alias glg='git log -E -i --grep'
alias gls='git log -S'
alias glf='git log --oneline --'

alias gs="git stash"
alias gsu="git stash -u"
alias gsg="git stash -u --keep-index"
alias gss="git stash save"
alias gsp="git stash pop"
alias gsl="git stash list"

alias gb="git branch"

alias gd="git diff --color=always"
alias gdc="git diff --cached --color=always"

alias gcp='git cherry-pick'
alias gcat='git cat-file'

alias grb="git rebase"
alias grbc="git rebase --continue"

alias gabort='git abort'
alias gcl="git clean -fi"

alias conflicted="git conflicted"

__git_complete g __git_main
__git_complete ga _git_add
__git_complete gc _git_commit
__git_complete gca _git_commit
__git_complete gph _git_push
__git_complete gbrem _git_push
__git_complete gpl _git_pull
__git_complete gco _git_checkout
__git_complete gr _git_reset
__git_complete gs _git_stash
__git_complete gd _git_diff
__git_complete gb _git_branch
__git_complete grb _git_rebase
__git_complete gcl _git_clean
__git_complete gd _git_diff
__git_complete gcp _git_cherry_pick

g() {
  if ! [ -d .git ] && [ "$1" != 'init' ]; then
    echo 'No git repository'
  elif [[ $# -eq 0 ]] ; then
    git status -s
  else
    git $@
  fi
}
