#!/bin/bash

source /usr/share/bash-completion/completions/git

alias g='g'
alias ga="git add"
alias gaa="git add *"
alias gc="git commit"
alias gca="git commit -a"
alias gcan="git commit --amend --no-edit"
alias gph="git push"
alias gpl="git pull"
alias go="git checkout"
alias gob="git checkout -b"
alias gr="git reset"
alias gl="git log --pretty=format:\"%C(yellow)%h %C(magenta)%ad%Cred%d %Creset%s%Cblue [%cn]\" --decorate --date=short"
alias gs="git stash"
alias gsu="git stash -u"
alias gsp="git stash pop"
alias gb="git branch"
alias gd="git diff"
alias grb="git rebase"
alias gcl="git clean -fi"

alias galias="alias | grep git | grep -v galias | cut -d ' ' -f 2- | sed '/=/s//|/' | tr \"'\" \" \" | column -s \"|\" -t"

__git_complete g __git_main
__git_complete ga _git_add
__git_complete gc _git_commit
__git_complete gca _git_commit
__git_complete gph _git_push
__git_complete gpl _git_pull
__git_complete go _git_checkout
__git_complete gr _git_reset
__git_complete gs _git_stash
__git_complete gd _git_diff
__git_complete gb _git_branch
__git_complete grb _git_rebase
__git_complete gcl _git_clean

g() {
  if ! [ -d .git ] && [[ $1 -ne 'init' ]]; then
    echo 'No git repository'
  elif [[ $# -eq 0 ]] ; then
    git status -s
  else
    git $@
  fi
}
