#!/bin/bash

COLOR_RED="\033[0;91m"
COLOR_YELLOW="\033[0;33m"
COLOR_GREEN="\033[0;32m"
COLOR_OCHRE="\033[38;5;95m"
COLOR_BLUE="\033[0;34m"
COLOR_RESET="\033[0m"

two_last_dirs() {
  pwd | awk -F\/ '{print $(NF-1),$(NF)}' | sed 's/ /\//' | sed "s/\(home\/$(whoami)\|$(whoami)\)/~/"
}

PS1="\[$COLOR_GREEN\]\$(two_last_dirs)\[$COLOR_YELLOW\]"
PS1+="\[$COLOR_GREEN\] ❱ \[$COLOR_RESET\]"

export PS1
