#!/bin/bash

parse_git_branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

git_status() {
  status_porcelain="$(git status --porcelain 2> /dev/null)"
  stash=$([[ `git stash list 2> /dev/null` ]] && echo -n "$")

  if [[ $(grep "^[^??]" <<< $status_porcelain ) ]]; then
    status=$(echo "*")
  elif [[ $(grep "^?? [^\.]" <<< $status_porcelain ) ]]; then
    status=$(echo "+")
  fi

  [[ $status || $stash ]] && echo "[$stash$status]"
}

export PS1="\[\e[32m\]\w\[\e[33m\]\$(parse_git_branch)\[\e[91m\]\$(git_status)\[\e[m\]: "
