#!/bin/bash

alias b='bundle exec'
alias r='bundle exec rails'
alias rc='bundle exec rails c'
alias rct='bundle exec rails c -e test'
alias dbc='bundle exec rails dbconsole'
alias dbm='bundle exec rails db:migrate'
alias dbr='bundle exec rails db:rollback'
alias rs='bundle exec rspec'
