#!/bin/bash

rvm_silence_path_mismatch_check_flag=1

export rvm_path="/home/$USER/.rvm"
[[ -s "/home/$USER/.rvm/scripts/rvm" ]] && source "/home/$USER/.rvm/scripts/rvm"
[[ -s "/usr/local/rvm/scripts/rvm" ]] && source "/usr/local/rvm/scripts/rvm"
