#!/bin/bash

rvm_silence_path_mismatch_check_flag=1

if [ -d "/home/$USER/.rvm" ]; then
  export rvm_path="/home/$USER/.rvm"
elif [ -d "/usr/local/rvm" ]; then
  export rvm_path="/usr/local/rvm"
fi

source "$rvm_path/scripts/rvm"
