#!/bin/bash

# Vim

alias v="v"
alias bv="bv"

v() {
  if [[ $# -eq 0 ]] ; then
    vim $(__fzf_preview)
  else
    vim $@
  fi
}

bv() {
  if [[ $# -eq 0 ]] ; then
    bundle e vim $(__fzf_preview)
  else
    bundle e vim $@
  fi
}

__fzf_preview() {
 fzf
}
