#!/bin/bash

alias c='clear'
alias b='bundle exec'
alias v='vim'
alias bv='bundle exec vim'
alias rc='bundle exec rails c'
alias rd='bundle exec rails dbconsole'
alias rdm='bundle exec rails db:migrate'
alias rdr='bundle exec rails db:rollback'
alias rs='bundle exec rspec'

# xclip clipboard
alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'

# colorize grep
alias grep="grep --color=auto"
alias fgrep="fgrep --color=auto"
alias egrep="egrep --color=auto"

# git aliases
alias ga="git add"
alias gaa="git add *"
alias gc="git commit"
alias gca="git commit -a"
alias gcan="git commit --amend --no-edit"
alias gph="git push"
alias gpl="git pull"
alias go="git checkout"
alias gob="git checkout -b"
alias gr="git reset"
alias gl="git log --pretty=format:\"%C(yellow)%h %ad%Cred%d %Creset%s%Cblue [%cn]\" --decorate --date=short"
alias gs="git stash"
alias gsu="git stash -u"
alias gsp="git stash pop"
alias gb="git branch"
alias gd="git diff"
alias gcl="git clean -fi"

# list git aliases
alias galias="alias | grep git | grep -v galias | cut -d ' ' -f 2- | sed '/=/s//|/' | tr \"'\" \" \" | column -s \"|\" -t"

# git aliases autocompletion
__git_complete g __git_main
__git_complete ga _git_add
__git_complete gc _git_commit
__git_complete gca _git_commit
__git_complete gph _git_push
__git_complete gpl _git_pull
__git_complete go _git_checkout
__git_complete gr _git_reset
__git_complete gs _git_stash
__git_complete gd _git_diff
__git_complete gcl _git_clean
